version: "3.7"

services:
  sample:
    container_name: casuallycool
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
    environment:
      - WATCHPACK_POLLING=true
